cloudogu/gitops-playground

- scm-manager/initscmm.sh
- scripts/apply.sh
- adds gitopsbuildlib repo in scmm through initscmm.sh
- clones gitopsbuildlib from github with --bare and pushes to scmm with --mirror to get all tags
Signed-off-by: Philipp Markiewka <philipp.markiewka@cloudogu.com>
> adds gitopsbuildlib repo

- applications/nginx/fluxv1/Jenkinsfile
- applications/petclinic/fluxv1/helm/Jenkinsfile
- applications/petclinic/fluxv1/helm/index.html
- applications/petclinic/fluxv1/plain-k8s/Jenkinsfile
Signed-off-by: Marek Markiewka <marek.markiewka@cloudogu.com>
> added fileconfigmaps to petclinic helm

- applications/nginx/fluxv1/Jenkinsfile
- applications/petclinic/argocd/plain-k8s/Jenkinsfile
- applications/petclinic/fluxv1/helm/Jenkinsfile
- applications/petclinic/fluxv1/plain-k8s/Jenkinsfile
- applications/petclinic/fluxv2/plain-k8s/Jenkinsfile
- scripts/scm-manager/init-scmm.sh
Signed-off-by: Frederick Roy <frederick.roy@cloudogu.com>
> remove anonymousMode for scmm; usage of a dev-branch gitops-build-lib

- applications/nginx/fluxv1/Jenkinsfile
- applications/petclinic/fluxv1/helm/Jenkinsfile
- applications/petclinic/fluxv1/plain-k8s/Jenkinsfile
Signed-off-by: Marek Markiewka <marek.markiewka@cloudogu.com>
> testing fix in cesbuildlib

- applications/nginx/argocd/Jenkinsfile
- applications/nginx/fluxv1/Jenkinsfile
- applications/petclinic/argocd/helm/Jenkinsfile
- applications/petclinic/argocd/plain-k8s/Jenkinsfile
- applications/petclinic/fluxv1/helm/Jenkinsfile
- applications/petclinic/fluxv1/plain-k8s/Jenkinsfile
- jenkins/values.yaml
Signed-off-by: Marek Markiewka <marek.markiewka@cloudogu.com>
> fixed gitopsTool typo

- README.md
- applications/nginx/argocd/Jenkinsfile
- applications/nginx/fluxv1/Jenkinsfile
- applications/petclinic/argocd/helm/Jenkinsfile
- applications/petclinic/argocd/plain-k8s/Jenkinsfile
- applications/petclinic/fluxv1/helm/Jenkinsfile
- applications/petclinic/fluxv1/plain-k8s/Jenkinsfile
- jenkins/values.yaml
- scripts/apply.sh
apply with: 
`scripts/apply.sh -x --argocd --kubectl-image somefancykubectlimage --helm-image somefancyhelmimage --yamllint-image somefancyyamllintimage`
check:
http://localhost:9091/scm/repo/argocd/petclinic-helm/code/sources/main/Jenkinsfile/#line-85
or
http://localhost:9091/scm/repo/argocd/petclinic-plain/code/sources/main/Jenkinsfile/#line-85
> adds configurable images for the gitops-build-lib config

- applications/nginx/argocd/Jenkinsfile
- applications/nginx/fluxv1/Jenkinsfile
- docs/gke.md
Signed-off-by: Marek Markiewka <marek.markiewka@cloudogu.com>
> removed timeout step so builds won't fail

- README.md
I'm convinced someone who finds this repo wants to know what it is before starting a discussion :-P
> README: Move link to community.

- Dockerfile
- applications/nginx/argocd/helm-jenkins/Jenkinsfile
- applications/nginx/fluxv1/Jenkinsfile
- exercises/nginx-validation/Jenkinsfile
also bumps nginx helm chart version, because bitnami removed older versions
> bumps alpine to fix critical CVEs

- applications/cluster-resources/monitoring/prometheus-stack-helm-values.yaml
- docs/developers.md
- src/main/groovy/com/cloudogu/gitops/ApplicationConfigurator.groovy
- src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy
- src/main/groovy/com/cloudogu/gitops/features/deployment/ArgoCdApplicationStrategy.groovy
- src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/deployment/ArgoCdApplicationStrategyTest.groovy
> Upgrade kube-prometheus-stack to 42.0.3

- Dockerfile
- Jenkinsfile
- pom.xml
- scripts/e2e.groovy
- src/main/groovy/com/cloudogu/gitops/Application.groovy
- src/main/groovy/com/cloudogu/gitops/features/Vault.groovy
- src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy
- src/main/groovy/com/cloudogu/gitops/graal/groovy/GroovyApplicationRegistrationFeature.java
- src/main/groovy/com/cloudogu/gitops/graal/groovy/GroovyDgmClassesRegistrationFeature.java
- src/main/groovy/com/cloudogu/gitops/graal/jgit/JGitReflectionFeature.java
- src/main/groovy/com/cloudogu/gitops/scmm/ScmmRepo.groovy
- src/main/groovy/com/cloudogu/gitops/utils/FileSystemUtils.groovy
- src/test/groovy/com/cloudogu/gitops/features/VaultTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
- src/test/groovy/com/cloudogu/gitops/utils/ScmmRepoTest.groovy
Which also updates Groovy to version 4
> Update Micronaut to 4.0.1

- pom.xml
- scripts/utils.sh
- src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
- src/main/groovy/com/cloudogu/gitops/dependencyinjection/HttpClientFactory.groovy
- src/main/groovy/com/cloudogu/gitops/dependencyinjection/RetrofitFactory.groovy
- src/main/groovy/com/cloudogu/gitops/jenkins/JenkinsConfiguration.groovy
- src/main/groovy/com/cloudogu/gitops/jenkins/JenkinsConfigurationAdapter.groovy
- src/test/groovy/com/cloudogu/gitops/common/MockWebServerHttpsFactory.groovy
- src/test/groovy/com/cloudogu/gitops/destroy/DestroyerDependencyInjectionTest.groovy
- src/test/groovy/com/cloudogu/gitops/jenkins/ApiClientTest.groovy
- src/test/groovy/com/cloudogu/gitops/scmm/api/UsersApiTest.groovy
We were not respecting --insecure for the Jenkins HTTP client.
> Fix --insecure for creating jenkins user

- Jenkinsfile
> Remove trivy version from Jenkinsfile

- src/main/groovy/com/cloudogu/gitops/okhttp/RetryInterceptor.groovy
Previously, retries were not logged, as the chain responsible for handling retries and logging were executing in order
1. RetryInterceptor
2. LoggingInterceptor
As a result, the LoggingInterceptor would only get the result of the RetryInterceptor. That result is the successful request, not every retried request.
Thus, we implement logging retries ourselves.
> Improve logging for HTTP retries

- applications/argocd/nginx/helm-jenkins/README.md
- argocd/cluster-resources/README.md
- exercises/broken-application/README.md
> Add READMEs to all example apps

- Dockerfile
- README.md
- argocd/argocd/argocd/Chart.lock
- argocd/argocd/argocd/Chart.yaml
- argocd/argocd/argocd/values.ftl.yaml
- scripts/apply.sh
- scripts/init-cluster.sh
- src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy
- src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
- terraform/vars.tf
changed K8s-Version to 1.29 and argocd to 2.10.1
> Update ArgoCD and Kubernetes

- Dockerfile
- src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy
- src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy
- src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy
- src/main/groovy/com/cloudogu/gitops/features/ScmManager.groovy
- src/main/groovy/com/cloudogu/gitops/scmm/ScmmRepo.groovy
- src/main/groovy/com/cloudogu/gitops/utils/CommandExecutor.groovy
- src/test/groovy/com/cloudogu/gitops/features/ScmManagerTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/deployment/ArgoCdApplicationStrategyTest.groovy
- src/test/groovy/com/cloudogu/gitops/utils/ScmmRepoTest.groovy
The author for the inital commits can now be defined with the parameters `--git-name` and `--git-email`.
> Add paramters to define the gitAuthor 

- .github/workflows/create-release.yml
- docs/developers.md
- src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy
- src/test/groovy/com/cloudogu/gitops/ApplicationConfiguratorTest.groovy
This is mainly for local development
> Minor fixes

- exercises/broken-application/broken-application.ftl.yaml
- src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
and fix service type.
You can validate if it works by solving this exercise:
https://cloudogu.github.io/workshop-cloudland24/#/3/1
> Exercise broken app: Add ingress

- Jenkinsfile
- README.md
- scripts/init-cluster.sh
add binding for k8s exposed services to 127.0.0.1 instead of default 0.0.0.0
> Limit accessibilty to localhost interface

- .dockerignore
- Dockerfile
- pom.xml
- src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy
- src/main/groovy/com/cloudogu/gitops/cli/package-info.java
- src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy
This is helpful to know when applying GOP and also satisfies potential legal requirements.
> Print version and license from CLI

- src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy
fixing duplicates in commit message with active network policies 
Example:
> Fix netPols commit message

- docs/developers.md
- src/main/groovy/com/cloudogu/gitops/Feature.groovy
* Dev docs for two registries/airgapped/image pull secrets
* Feature.groovy to make developping new features easier
> Extend dev docs

- docs/configuration.schema.json
- scm-manager/values.ftl.yaml
- src/main/groovy/com/cloudogu/gitops/Feature.groovy
- src/main/groovy/com/cloudogu/gitops/config/Config.groovy
- src/main/groovy/com/cloudogu/gitops/features/CertManager.groovy
- src/main/groovy/com/cloudogu/gitops/features/ExternalSecretsOperator.groovy
- src/main/groovy/com/cloudogu/gitops/features/IngressNginx.groovy
- src/main/groovy/com/cloudogu/gitops/features/Mailhog.groovy
- src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy
- src/main/groovy/com/cloudogu/gitops/features/Registry.groovy
- src/main/groovy/com/cloudogu/gitops/features/ScmManager.groovy
- src/main/groovy/com/cloudogu/gitops/features/Vault.groovy
- src/main/groovy/com/cloudogu/gitops/utils/FileSystemUtils.groovy
- src/test/groovy/com/cloudogu/gitops/features/CertManagerTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/ExternalSecretsOperatorTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/IngressNginxTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/MailhogTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/RegistryTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/ScmManagerTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/VaultTest.groovy
- Introduced the `helmValues` function for SCM Manager to simplify configuration management.
- Set `initialDelaySeconds` directly in values giving more time for startup.
- Applied the same Helm values functionality to other features for consistency across the helm charts.
> Adds Helm values functionality to SCM Manager and other features

- src/main/groovy/com/cloudogu/gitops/features/CertManager.groovy
- src/main/groovy/com/cloudogu/gitops/features/ExternalSecretsOperator.groovy
- src/main/groovy/com/cloudogu/gitops/features/IngressNginx.groovy
- src/main/groovy/com/cloudogu/gitops/features/Mailhog.groovy
- src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy
- src/main/groovy/com/cloudogu/gitops/features/Vault.groovy
- src/main/groovy/com/cloudogu/gitops/utils/MapUtils.groovy
- src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy
feat: allowing to merge null values into maps via deepMerge
bug: fixing scm path
> Adds the possibility to deepmerge null values if necessary

- docs/developers.md
- src/main/groovy/com/cloudogu/gitops/config/Config.groovy
- src/test/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliTest.groovy
Updating Helm Chart Version for Prometheus Stack.
> Updating Prometheus Helm Chart to 69.7.4

- argocd/argocd/applications/argocd.ftl.yaml
- argocd/argocd/applications/bootstrap.ftl.yaml
- argocd/argocd/applications/cluster-resources.ftl.yaml
- argocd/argocd/applications/example-apps.ftl.yaml
- argocd/argocd/applications/projects.ftl.yaml
- argocd/argocd/argocd/values.ftl.yaml
- argocd/argocd/operator/argocd.ftl.yaml
- argocd/argocd/projects/argocd.ftl.yaml
- argocd/argocd/projects/cluster-resources.ftl.yaml
- argocd/argocd/projects/example-apps.ftl.yaml
- argocd/cluster-resources/argocd/misc.ftl.yaml
- docs/configuration.schema.json
- docs/developers.md
- pom.xml
- scripts/scm-manager/init-scmm.sh
- src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy
- src/main/groovy/com/cloudogu/gitops/config/Config.groovy
- src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy
- src/main/groovy/com/cloudogu/gitops/dependencyinjection/RetrofitFactory.groovy
- src/main/groovy/com/cloudogu/gitops/features/Jenkins.groovy
- src/main/groovy/com/cloudogu/gitops/features/ScmManager.groovy
- src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy
- src/main/groovy/com/cloudogu/gitops/scmm/ScmmRepo.groovy
To preserve code for future use, we will integrate the GitLab API as a replacement for SCM Manager in the GOP. However, enabling this feature is currently not possible.
> Experimental GitLab API

- docs/developers.md
- src/main/groovy/com/cloudogu/gitops/config/Config.groovy
- src/test/groovy/com/cloudogu/gitops/features/IngressNginxTest.groovy
Fixes cve-2025-1974
https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974/
> Upgrade ingress-nginx

- argocd/argocd/argocd/templates/allow-namespaces.ftl.yaml
- docs/developers.md
> Adapt netpols to prefix

- argocd/argocd/argocd/values.ftl.yaml
- argocd/cluster-resources/misc/monitoring/scmm-dashboard.ftl.yaml
- scm-manager/values.ftl.yaml
- scripts/scm-manager/init-scmm.sh
- src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy
- src/main/groovy/com/cloudogu/gitops/features/CertManager.groovy
- src/main/groovy/com/cloudogu/gitops/features/ExternalSecretsOperator.groovy
- src/main/groovy/com/cloudogu/gitops/features/IngressNginx.groovy
- src/main/groovy/com/cloudogu/gitops/features/Mailhog.groovy
- src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy
- src/main/groovy/com/cloudogu/gitops/features/ScmManager.groovy
- src/main/groovy/com/cloudogu/gitops/features/Vault.groovy
- src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy
- src/main/groovy/com/cloudogu/gitops/scmm/ScmmRepo.groovy
- src/test/groovy/com/cloudogu/gitops/features/CertManagerTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/ExternalSecretsOperatorTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/IngressNginxTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/MailhogTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/ScmManagerTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/VaultTest.groovy
- src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
- src/test/groovy/com/cloudogu/gitops/integration/GOPSmoketestsIT.groovy
Rename scmm-scm-manager to scmm for clarity
> Simplify internal SCM-Manager URL

- argocd/argocd/argocd/values.ftl.yaml
- argocd/argocd/operator/argocd.ftl.yaml
- argocd/argocd/projects/argocd.ftl.yaml
- src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
Argocd had has a list of allowed repositories. This list is replaces by '*' to allow future repos.
> Remove repo restriction for root project argocd
