README.md, scripts/init-cluster.sh
Following #1, I tried this on a plain ubuntu (I used multipass) and it actually failed when there was no `kubeconfig`:   
`./scripts/init-cluster.sh: line 97: /home/ubuntu/.kube/config2: No such file or directory`
```
multipass launch --name gitops 20.04
multipass shell gitops
sudo apt update && sudo apt install -y docker.io
sudo usermod -aG docker ubuntu
exit
multipass shell gitops
git clone https://github.com/cloudogu/k8s-gitops-playground
cd k8s-gitops-playground
git switch feature/init-without-kubectl
yes | scripts/init-cluster.sh
```
This should fix it.
It also checks our only prerequisite left: docker binary present and fails otherwise.
=> Don't fail when there is no .kube dir

applications/nginx/argocd/Chart.yaml
Signed-off-by: Philipp Markiewka <philipp.markiewka@cloudogu.com>
=> Set apiVersion to v2, so that argoCD uses Helm3 for deployment

jenkins/values.yaml, scripts/jenkins/init-jenkins.sh
By upgrading to (almost) latest helm chart version and explicitly installing plugin dependencies.
Note: Didn't upgrade to latest helm chart version because it lead to errors on build, such as the following:
` Remote call to JNLP4-connect connection to jenkins-agent.default.svc.cluster.local/10.43.179.183:50000`
=> Jenkins: Fix failing K8s agent builds.

scripts/jenkins/plugins/plugins.txt
- The install plugins script tries to download the latest plugin dependencies. In this case the latest dependency plugin "workflow-durable-task-step" is not compatible with the used jenkins version anymore
Signed-off-by: pmarkiewka <philipp.markiewka@cloudogu.com>
=> pin plugin workflow-durable-task-step to fix corrupted dependencies

Dockerfile, scm-manager/values.yaml, scripts/apply.sh, scripts/destroy.sh, scripts/scm-manager/init-scmm.sh
Upgrades dependencies, mainly to address CVE-2022-21449: Psychic Signatures in Java 17+.
Most notably: SCM-Manager moves from 2.20 to 2.33
Test image available: `ghcr.io/cloudogu/gitops-playground:142302c`.
=> Upgrade dependencies

Dockerfile, README.md
TIL `docker run --pull=always`
Build broke, because `https://zlib.net/zlib-1.2.12.tar.gz` no longer exists. So had to fix this, even though this mere documentation change did not have anything to do with it 🙄
=> Simplify TLDR

Dockerfile, scripts/jenkins/init-jenkins.sh
* Jenkins Chart 4.2.9 is no longer working (even with default values) because of plugin dependency `Plugin workflow-aggregator ... depends on configuration-as-code:1559.v38a_b_2e3b_6b_b_7, but there is an older version defined on the top level`
* Avoid  CVE-2022-37865 in ivy for dev image
Cherry picks from #98
=> Upgrade Jenkins and fix vuln

Dockerfile, Jenkinsfile, pom.xml, scripts/apply-ng.sh
The moving tag `test`  allows us to have a constant image tag that can be used to review features in customer environments before merging them to main.
=> Push branch "test" as image tag "test" + Get rid of CVE-2022-1471

.gitignore, docs/developers.md, scripts/apply-ng.sh, scripts/jenkins/init-jenkins.sh
Running apply.sh without container used to work unofficially, for development.
It stopped in 4d95f75e, when we (probably unintentionally) commented a line in init-jenkins.sh.
Later, in a9c1a160, we got rid of the need for a local groovy installation, which also influences the apply.sh, when run locally.
This commit updates the developers.md and fixes some small issues to allow local apply.sh execution for the sake of faster development speed.
Important: After this PR, the `dev` image should still work.
=> Allow running apply.sh without container

Jenkinsfile
As we're increasingly running into timeouts when sharing the agents with other jobs that also require a lot of CPU, we're now running dedicated machines per Job.
This also resolves any potential concurrency issues in `Jenkinsfile` that we spent a fortune to avoid :smile:
=> Jenkins: Run on dedicated build agents

Jenkinsfile, scripts/scm-manager/init-scmm.sh
Avoids errors caused by accidental breaking change in scmm-review-plugin with gitops-build-lib.
The problem was fixed in 2.27.1, which requires SCM-Manager 2.44.0.
=> Upgrade SCMM

applications/argocd/petclinic/helm/k8s/values-shared.ftl.yaml, exercises/petclinic-helm/k8s/values-shared.ftl.yaml
Separate PRs that were not in conflict with each other changed how LoadBalancer/NodePort were handled. The conflict didn't show in git, however it introduced a bug on main.
=> Fix merge conflict on main

src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy, src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy
We missed that we set the path including the /scm prefix. Therefore, we must not prepend the path to the prometheus endpoint with /scm.
This is different to Jenkins. Jenkins runs without a path prefix.
=> Fix path to SCM-Manager in prometheus scrape config

applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml, scripts/jenkins/jenkins-REST-client.sh
A bug in curl (https://github.com/curl/curl/issues/11486) broke the
jenkins plugin installation. We introduced a workaround in https://github.com/cloudogu/gitops-playground/commit/16300dea3434313840533257838728e3b8aeddae.
A fix for curl is released and we can remove the workaround now.
=> Remove workaround for curl 8.2.0 

argocd/argocd/argocd/values.ftl.yaml, src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
We were not respecting the --insecure flag in Argo CD. As a result, Argo CD would not talk to SCM-Manager and would fail with the following error:
rpc error: code = Unknown desc = Get "https://something/scm/repo/argocd/argocd/info/refs?service=git-upload-pack": x509: certificate signed by unknown authority
=> Fix using --insecure and --argocd

applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml
There are policies within azure that deny containers that run as a non-default user when `allowPrivilegeEscalation` was not set. https://store.policy.core.windows.net/kubernetes/container-no-privilege-escalation/v3/template.yaml
=> Fix starting grafana when using Azure Gatekeeper

applications/cluster-resources/mailhog-helm-values.ftl.yaml, applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml, argocd/argocd/argocd/values.ftl.yaml, src/main/groovy/com/cloudogu/gitops/features/Mailhog.groovy, src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy, src/main/groovy/com/cloudogu/gitops/features/Vault.groovy, src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy, src/test/groovy/com/cloudogu/gitops/features/MailhogTest.groovy, src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy, src/test/groovy/com/cloudogu/gitops/features/VaultTest.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
In #147 we implemented ingresses for all applications. The parameter --argocd-url was already used beforehand for urls in notifications.
In #147 we mistakenly assumed that the url would only include the hostname without protocol or paths.
Here, we fix this by parsing the URL and extracting the host for the ingress configuration.
=> Fix specifying protocol for ingress urls

src/main/groovy/com/cloudogu/gitops/dependencyinjection/RetrofitFactory.groovy, src/main/groovy/com/cloudogu/gitops/jenkins/ApiClient.groovy, src/main/groovy/com/cloudogu/gitops/jenkins/JobManager.groovy, src/main/groovy/com/cloudogu/gitops/okhttp/RetryInterceptor.groovy, src/test/groovy/com/cloudogu/gitops/jenkins/ApiClientTest.groovy, src/test/groovy/com/cloudogu/gitops/okhttp/RetryInterceptorTest.groovy
We were running into an issue where jenkins was restarted after we fetched a crumb but before we used that crumb.
1. Fetch crumb
2. Restart Jenkins
3. Use crumb e.g. in /scriptText
Due to the restart, the crumb is invalid (either due to the crumb itself or the associated session).
The previous handling would then retry the /scriptText request without refreshing the crumb.
We changed the behaviour in the following responsibilities:
1. RetryInterceptor is responsible for retrying HTTP level issues (e.g. status codes or timeouts)
2. ApiClient is responsible for application (aka Jenkins) level issues (i.e. HTTP status code 401 or 403 during restarts or invalid crumbs)
As a result, we don't leak special cases for Jenkins into the RetryInterceptor anymore and it can be used for SCMM APIs as …
=> Improved retrying for invalid jenkins crumbs

scripts/utils.sh
rather than continuing with the next step.
This only affects when not running with -x
closes #7
=> Stop execution when a step fails

Jenkinsfile, README.md, docker-registry/values.yaml, docs/developers.md, docs/k3d.md, scripts/apply.sh, scripts/init-cluster.sh
Most breaking changes are abstracted by init-cluster.sh
Except: k3d now writes kubeconfig to different folder.
* Used to be: ` ~/.k3d`
* Now is: ` ~/.config/k3d/`
* This made it necessary to adapt the TLDR command in our README
* We could move the file in init-cluster to avoid breaking change but then we would use a non-default folder. See 217a172.
I used the chance to change the logic of the init-cluster.sh to install k3d without needing root permissions to `.local/bin`.
I think not needing root/sudo makes a nicer UX and also allows use to reuse this logic in Jenkinsfile.
The only downside I see is that `.local/bin` might not be in the users `PATH`. See 7740fe1.
You can try the latest like so:
```bash
COMMIT=7740fe1
bash <(curl -s \ …
```
=> k3d: Upgrade to 5.x

applications/cluster-resources/mailhog-helm-values.ftl.yaml, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/features/Mailhog.groovy, src/test/groovy/com/cloudogu/gitops/features/MailhogTest.groovy
Supersedes #142, as there were breaking changes that made it easier to re-implement.
In the meantime the playground was extended, providing the option to template our mailog values.yaml.
This PR uses this option, preparing for parameterization of the image version.
=> Use a mailhog image without CVEs

Jenkinsfile
The merge commit of a PR at github has a git user with an email address at `users.noreply.github.com`.
This leads to Jenkins mails on failed commits being not delivered. So: send an additional mail to a list of devs defined in Jenkins. A failed main branch deserves urgent attention.
=> Jenkinsfile: Send additional mail to devs if main fails

applications/argocd/petclinic/Dockerfile.ftl, applications/argocd/petclinic/helm/Jenkinsfile.ftl, applications/argocd/petclinic/plain-k8s/Jenkinsfile.ftl, applications/argocd/petclinic/plain-k8s/k8s/staging/deployment.yaml, docs/configuration.schema.json, exercises/petclinic-helm/Jenkinsfile.ftl, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy, src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy, src/main/groovy/com/cloudogu/gitops/utils/TemplatingEngine.groovy, src/test/groovy/com/cloudogu/gitops/config/ConfigToConfigFileConverterTest.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy, src/test/groovy/com/cloudogu/gitops/utils/TemplatingEngineTest.groovy
Why? Air-gapped mode.
Buildpacks load multiple dependencies from different sources, some of them directly from GitHub. This just seems not to work in air-gapped envs.
Our Dockerfile has only one dependency: the base image. This can now be replaced using a param or config option.
The drawback: buildpacks provide a rather easy way of getting deterministic builds, which we will lose for now.
While one it: Implement k8s appOps best practices for security context in petclinic-plain. This should make sure we can also run on OpenShift.
=> Petclinic: Switch from buildpacks to Dockerfile

Dockerfile
This change adds the -t 3 flag to the wget command, which means the download attempt will be retried up to three times if connection errors occur.
=> Fix gpg import bug for helm

applications/argocd/petclinic/helm/Jenkinsfile.ftl, applications/argocd/petclinic/plain-k8s/Jenkinsfile.ftl, docs/configuration.schema.json, docs/developers.md, exercises/petclinic-helm/Jenkinsfile.ftl, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy, src/main/groovy/com/cloudogu/gitops/destroy/JenkinsDestructionHandler.groovy, src/main/groovy/com/cloudogu/gitops/features/Jenkins.groovy, src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy, src/test/groovy/com/cloudogu/gitops/ApplicationConfiguratorTest.groovy, src/test/groovy/com/cloudogu/gitops/config/ConfigToConfigFileConverterTest.groovy, src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
Useful for air-gapped environments.
`developers.md` contains info on how to test this feature.
Expected behavior is that after the Jenkins builds of the two petclinics are done, the two applications are running inside the cluster basing on `localhost:30000/push/` images:
```shell
kubectl get deployment -n example-apps-staging -o=jsonpath="{range .items[*]}{'\n'}{.metadata.name}{':\t'}{range .spec.template.spec.containers[*]}{.image}{', '}{end}{end}"
spring-petclinic-plain: localhost:30000/push/spring-petclinic-plain:202404261302-a026e65-main,
spring-petclinic-helm-springboot:       localhost:30000/push/spring-petclinic-helm:202404261303-3bbd2a9-main,
```
=> Introduce option for two registries

Jenkinsfile, README.md, docs/developers.md, docs/k3d.md, scripts/init-cluster.sh
* Change: Bind to localhost:80 without parameters, i.e. `--bind-localhost=80`
```bash
scripts/init-cluster.sh
```
* Achieve former behavior without params:
```bash
scripts/init-cluster.sh --bind-localhost
```
* Unchanged: Bind to another ingress port
```bash
scripts/init-cluster.sh --bind-localhost=8080
```
* New Feature: Bind additional ports, e.g. reach Jenkins, SCMM and Argo CD without ingress via localhost:9090, etc.
```
scripts/init-cluster.sh --bind-ports=9090:9090,9091:9091,9092:9092
````
=> init-cluster.sh: Bind Ingress by default and allow for binding additional ports

applications/argocd/nginx/helm-jenkins/k8s/values-shared.ftl.yaml, applications/argocd/nginx/helm-umbrella/values.ftl.yaml, applications/argocd/petclinic/helm/k8s/values-shared.ftl.yaml, applications/argocd/petclinic/plain-k8s/k8s/production/deployment.ftl.yaml, applications/argocd/petclinic/plain-k8s/k8s/staging/deployment.ftl.yaml, applications/cluster-resources/ingress-nginx-helm-values.ftl.yaml, applications/cluster-resources/mailhog-helm-values.ftl.yaml, applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml, applications/cluster-resources/secrets/external-secrets/values.ftl.yaml, exercises/broken-application/broken-application.ftl.yaml, exercises/nginx-validation/k8s/values-shared.ftl.yaml, exercises/petclinic-helm/k8s/values-shared.ftl.yaml, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy, src/main/groovy/com/cloudogu/gitops/features/ExternalSecretsOperator.groovy, src/main/groovy/com/cloudogu/gitops/features/IngressNginx.groovy, src/main/groovy/com/cloudogu/gitops/features/Mailhog.groovy, src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy, src/main/groovy/com/cloudogu/gitops/features/Vault.groovy, src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy, src/test/groovy/com/cloudogu/gitops/features/ExternalSecretsOperatorTest.groovy, src/test/groovy/com/cloudogu/gitops/features/IngressNginxTest.groovy, src/test/groovy/com/cloudogu/gitops/features/MailhogTest.groovy, src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy, src/test/groovy/com/cloudogu/gitops/features/VaultTest.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
Current behavior is now opt-in: `--podResources` enables resource objects in all (well, most) pods.
This makes local execution of some apps like petclinic faster.
Maybe it will also lag on machine with less RAM or CPU. We'll see!
To avoid conflicts, this bases on #197. Please merge 197 first.
=> Disable pod resources by default

src/main/groovy/com/cloudogu/gitops/utils/K8sClient.groovy, src/test/groovy/com/cloudogu/gitops/utils/K8sClientTest.groovy, src/test/groovy/com/cloudogu/gitops/utils/NetworkingUtilsTest.groovy
K8sClient.waitForNode(): The method name claimed something the method did not do - waiting.
Before d2f218c1 / #174 we had a bash method of the same name that actually waited.
It was called before the Groovy code was called.
So all those years `K8sClient.waitForNode()` lied about its implementation, but it was no problem.
After the bash implementation was gone, however, our build started to become flaky with these kinds of errors:
```
TRACE c.c.gitops.utils.CommandExecutor - Executing command: '[kubectl, get, node, -oname]' 
TRACE c.c.gitops.utils.CommandExecutor - Executing command: '[head, -n1]'
TRACE c.c.gitops.utils.CommandExecutor - Executing command: '[kubectl, get, , --template='{{range .status.addresses}}{{ if eq .type "InternalIP" }}{{.address}}{{break}}{{end}}{{end}}']' 11:34:12 …
```
=> Fix waiting for node on startup

applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml
This allows application to create ServiceMonitors in their own namespace .
Fits much better with our least privilege and multi-tenancy approaches.
You can validate if it works by solving this exercise:
https://cloudogu.github.io/workshop-cloudland24/#/exercise-monitoring
=> Prometheus: watch CRs in all namespaces

Dockerfile, docs/developers.md, scripts/apply-ng.sh, src/main/groovy/com/cloudogu/gitops/Application.groovy, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliMain.groovy, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliMainScripted.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy, src/main/groovy/com/cloudogu/gitops/destroy/Destroyer.groovy, src/main/groovy/com/cloudogu/gitops/features/Jenkins.groovy, src/test/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliMainScriptedTest.groovy, src/test/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliMainTest.groovy, src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy
A collection of fixes that are necessary to run GOP in environments without cluster-admin privileges.
=> Minor fixes for least privilege environments

src/main/groovy/com/cloudogu/gitops/features/deployment/ArgoCdApplicationStrategy.groovy
23fb76a1 actually starts to interpret groovy code. Before, we unknowingly
executed the bytecode (class files) from the jar.
So we never knew about this bug:
`ArgoCdApplicationStrategy.groovy` ran `Path.text` even though Path in groovy does not have a text property.
The compiler somehow seems to make this right but the groovy interpreter does not 🤷‍♂️
Exception was as follows:
```
❯ docker run --rm -t -u $(id -u)  --pull=always \
-v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
--net=host \
ghcr.io/cloudogu/gitops-playground:a19d91f-dev --yes --argocd  --ingress-nginx --base-url=http://localhost
a19d91f-dev: Pulling from cloudogu/gitops-playground
Digest: sha256:5188edab4e513b531922ff6b63df24c4224f4c165fdc2657cd28d33e3a5386e0
Status: Image is up to date for …
```
=> Fix dev image

applications/argocd/petclinic/helm/Jenkinsfile.ftl, applications/argocd/petclinic/plain-k8s/Jenkinsfile.ftl, docs/configuration.schema.json, docs/developers.md, exercises/petclinic-helm/Jenkinsfile.ftl, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy, src/main/groovy/com/cloudogu/gitops/destroy/JenkinsDestructionHandler.groovy, src/main/groovy/com/cloudogu/gitops/features/Jenkins.groovy, src/test/groovy/com/cloudogu/gitops/ApplicationConfiguratorTest.groovy, src/test/groovy/com/cloudogu/gitops/config/ConfigToConfigFileConverterTest.groovy, src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
to decrease the number of parameters to improve user experience.
Migration:
* `registry-push-*` -> `registry-*`
* `registry-pull-*` -> `registry-proxy*`, `proxy-path` not in use right now.
=> BREAKING: Refactor params registry-push + pull to registry-proxy

applications/argocd/petclinic/helm/Jenkinsfile.ftl, applications/argocd/petclinic/plain-k8s/Jenkinsfile.ftl, exercises/petclinic-helm/Jenkinsfile.ftl, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
this feature allows users to set credentials for the registry when the twoRegistries option is enabled.
=> Pass proxyRegistry credentials to buildImages

applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml, applications/cluster-resources/monitoring/rbac/namespace-isolation-rbac.ftl.yaml, docs/configuration.schema.json, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliMainScripted.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy, src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy, src/test/groovy/com/cloudogu/gitops/config/ConfigToConfigFileConverterTest.groovy, src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy
After building locally you can test this feature like so:
```
docker run --rm -t -u $(id -u)  \
-v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
--net=host \
gitops-playground:dev --yes --argocd  --ingress-nginx --base-url=http://localhost --monitoring \
--namespace-isolation --mirror-repos \
--prometheus-config-reloader-image=quay.io/prometheus-operator/prometheus-config-reloader:v0.73.2 --prometheus-image=quay.io/prometheus/prometheus:v2.51.2 --prometheus-operator-image=quay.io/prometheus-operator/prometheus-operator:v0.73.2 --grafana-image=grafana/grafana:10.4.1  --grafana-sidecar-image=quay.io/kiwigrid/k8s-sidecar:1.26.1 \
--openshift --pod-resources -x 
```
This pretty much create the config we need in an air-gapped, namespace-isolated, least-privilege …
=> Implement namespaceIsolation for PrometheusStack

Dockerfile, Jenkinsfile, docs/k3d.md, scripts/init-cluster.sh
Fixes CVE-2024-24790 in kubectl.
Also update trivy in our build pipeline to make sure we find issues like these earlier.
I tested if the trivy update finds the CVE on a different branch (f1bc3c1e9c90a03f4a10d70e26e386a4908085a9) and later extracted this as a separate PR.
=> Update to kubernetes 1.29.8

scripts/init-cluster.sh
This resolves errors like this:
```
ERRO[0001] Failed Cluster Start: Failed to start server k3d-gitops-playground-server-0: Node k3d-gitops-playground-server-0 failed to get ready: error waiting for log line k3s is up and running from node 'k3d-gitops-playground-server-0': stopped returning log lines: node k3d-gitops-playground-server-0 is running=true in status=restarting 
ERRO[0001] Failed to create cluster >>> Rolling Back    
FATA[0002] Cluster creation FAILED, all changes have been rolled back! 
```
that have started to appear on 23 September 2024 🤷‍♂️
=> Upgrade k3d to 5.7.4

README.md, applications/argocd/petclinic/helm/Jenkinsfile.ftl, applications/argocd/petclinic/plain-k8s/Jenkinsfile.ftl, docs/configuration.schema.json, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy, src/test/groovy/com/cloudogu/gitops/config/ConfigToConfigFileConverterTest.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
Allowing passing down a custom maven build image. Additionally using the proxy registry if set. 
locally tested using :
--registry-proxy-url="localhost:9919"
--registry-proxy-username="test"
--registry-proxy-password="test"
--maven-image="maven:latest"
result: 
jenkinsfile displays proper values in SCMM for petclinic.
=> adding custom maven image and registry support

jenkins/namespaceJobTemplate.xml.ftl, scripts/jenkins/init-jenkins.sh, scripts/jenkins/jenkins-REST-client.sh, src/main/groovy/com/cloudogu/gitops/features/Jenkins.groovy, src/main/groovy/com/cloudogu/gitops/jenkins/JobManager.groovy, src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy, src/test/groovy/com/cloudogu/gitops/jenkins/JobManagerTest.groovy
This also fixes namePrefix issues, when starting the job and
updates from the legacy to the current `ScmManagerBranchDiscoveryTrait`.
The main reason is that this avoids the following error occurring in production
with Cloudogu Ecosystem:
```
++++ curl -s --cookie-jar /tmp/cookies --retry 3 --retry-delay 1 ... ++++ jq -rsc '(.[1] | .http_code|tostring), (.[0] | .crumb)' jq: parse error: Invalid numeric literal at line 4, column 14 +++ RESPONSE=
+++ EXIT_STATUS=5
+++ mapfile -t RESPONSE
+++ '[' 5 '!=' 0 ']'
+++ echo 'Creating Credentials failed with exit code: curl: 5, HTTP Status: ' +++ exit 5
++ curl -s -H 'Jenkins-Crumb:Creating Credentials failed with exit code: curl: 5, HTTP Status: ' --cookie /tmp/cookie ...-H Content-Type:text/xml --data '<?xml version="1.1" encoding="UTF-8"?>
``` …
=> Migrate Jenkins.createJob from bash to groovy

docs/developers.md, scripts/downloadHelmCharts.sh, src/main/groovy/com/cloudogu/gitops/config/Config.groovy
Updating the 'kube-prometheus-stack' from 58.2.1 to 66.2.1.
local testing for reviewer:
1. run ./scripts/downloadHelmCharts.sh and
2. run ./init-cluster.sh. 
3. run gop with params: 
--yes
--ingress-nginx
--argocd
--base-url=http://localhost
--monitoring
--cert-manager
-x
4. check if kubernetes runs the new chart with the new version:
kubectl get pods -l chart=kube-prometheus-stack-66.2.1 -n monitoring 
should output a running  kube-prometheus-stack-operator pod.
5. check if grafana is able to get data from prometheus. Visit Grafana and check metric logs.
6. deploy in airgapped mode and repeat step 4.
7.  execute
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" \
| tr -s '[[:space:]]' '\n' | sort | uniq \
| grep -v …
=> upgrading kube-prometheus-stack to 66.2.1

docs/configuration.schema.json, scm-manager/values.ftl.yaml, src/main/groovy/com/cloudogu/gitops/config/Config.groovy, src/main/groovy/com/cloudogu/gitops/features/ScmManager.groovy, src/test/groovy/com/cloudogu/gitops/features/ScmManagerTest.groovy
This change hopefully fixes the flaky integration tests found by https://github.com/cloudogu/gitops-playground/pull/237.
Allowing the SCMM more time to come alive could work out. If not additional measures are needed.
How to test locally:
1. rerun GOP
2. set a custom value for initialDelaySeconds in Config.groovy  under HelmConfigWithValues
3. run 'helm get manifest scmm | grep -A 10 livenessProbe'
4. the custom value should be displayed under livenessProbe
=> Increased livenessProbe initialDelaySeconds value to handle pipeline issues 

applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml, src/main/groovy/com/cloudogu/gitops/Application.groovy, src/main/groovy/com/cloudogu/gitops/Feature.groovy, src/main/groovy/com/cloudogu/gitops/FeatureWithImage.groovy, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliMainScripted.groovy, src/main/groovy/com/cloudogu/gitops/config/Config.groovy, src/main/groovy/com/cloudogu/gitops/features/PrometheusStack.groovy, src/main/groovy/com/cloudogu/gitops/utils/K8sClient.groovy, src/test/groovy/com/cloudogu/gitops/ApplicationConfiguratorTest.groovy, src/test/groovy/com/cloudogu/gitops/ApplicationTest.groovy, src/test/groovy/com/cloudogu/gitops/features/IngressNginxTest.groovy, src/test/groovy/com/cloudogu/gitops/features/PrometheusStackTest.groovy, src/test/groovy/com/cloudogu/gitops/utils/K8sClientTest.groovy
adding ServiceMonitorNamespaceSelectors to Prometheus.
removed duplicate getNamespace functions in Argo and Prometheus. Adding a Config param for active namespaces.
=> Namespace isolation: Specify Prometheus NamespaceSelectors

docs/configuration.schema.json, src/main/groovy/com/cloudogu/gitops/config/Config.groovy, src/test/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliTest.groovy, src/test/resources/errorConfig.yaml
Currently it is not possible to change config for Helm repos using repoURL, chart and version.
So we remove this config option in order to avoid frustrated users.
Why?
In order to effectively use a different OCI or helm repo, we would have to add it to the AppProject.  Whilst this is not impossible, it is not implemented, yet. 
Same goes for authentication: If the different OCI repo would need credentials we would have to add those to the Argo CD config, which is also not implemented, yet.
So for now, we remove the option.
Once we have a requirement to implement it, we implemented with proper UX.
=> BREAKING: Remove config options for Helm repo

applications/cluster-resources/mailhog-helm-values.ftl.yaml, applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml, src/test/groovy/com/cloudogu/gitops/features/MailhogTest.groovy
removing the default securityContext from the helm chart in Openshift. So Openshift will inject it's own SCC Contraints to the pods allowing the pods to run properly
=> feat: Mailhog SecurityContext removed in Openshift. Openshift will set own SCC constraints by this

applications/argocd/petclinic/helm/Jenkinsfile.ftl, applications/argocd/petclinic/plain-k8s/Jenkinsfile.ftl, src/main/groovy/com/cloudogu/gitops/config/Config.groovy
Petclinic: Disable database integration tests because they start docker images (which won't work in air-gapped envs and take a lot of time in demos)
=> Petclinic: disable DB integrationstests

src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/test/groovy/com/cloudogu/gitops/ApplicationConfiguratorTest.groovy, src/test/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCliTest.groovy
`--help`, `--version` and `--output-config` should work even when there is no working kube-context.
e.g. 
```bash
docker run ghcr.io/cloudogu/gitops-playground:0.10.0 --version
```
Fails with:
```
couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```
Because there is no working kube-context and initAndValidateConfig connects to k8s trying to find clusterBindAddress
This used to work before #241:
```
docker run ghcr.io/cloudogu/gitops-playground:0.8.0 --version
```
This PR fixes this issue.
=> CLI: Simple params no longer require k8s

src/main/groovy/com/cloudogu/gitops/utils/K8sClient.groovy, src/main/groovy/com/cloudogu/gitops/utils/NetworkingUtils.groovy, src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy, src/test/groovy/com/cloudogu/gitops/integration/GOPSmoketestsIT.groovy, src/test/groovy/com/cloudogu/gitops/utils/K8sClientForTest.groovy, src/test/groovy/com/cloudogu/gitops/utils/K8sClientTest.groovy, src/test/groovy/com/cloudogu/gitops/utils/NetworkingUtilsTest.groovy
Fixed two race condition issues:
- The integration test's start condition only checked for the presence of pods, while the test itself validated the Service. However, at that point, the Service was still in the process of being created.
- We waited for the node to return its name but did not wait for it to retrieve its IP. This occasionally caused flaky tests due to an empty IP value.
=> Fix integration tests for ingress-nginx

applications/cluster-resources/secrets/vault/values.ftl.yaml, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/Config.groovy, src/main/groovy/com/cloudogu/gitops/scmm/ScmmRepo.groovy, src/test/groovy/com/cloudogu/gitops/features/VaultTest.groovy
Usage of application password is application wide, now.
=> Fix application passwords, mailhog and vault ingress

Dockerfile, Jenkinsfile, README.md, docs/configuration.schema.json, docs/developers.md, scripts/scm-manager/init-scmm.sh, src/main/groovy/com/cloudogu/gitops/Application.groovy, src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy, src/main/groovy/com/cloudogu/gitops/config/Config.groovy, src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy, src/main/groovy/com/cloudogu/gitops/features/Content.groovy, src/main/groovy/com/cloudogu/gitops/features/Jenkins.groovy, src/main/groovy/com/cloudogu/gitops/features/Registry.groovy, src/main/groovy/com/cloudogu/gitops/features/ScmManager.groovy, src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy, src/test/groovy/com/cloudogu/gitops/ApplicationConfiguratorTest.groovy, src/test/groovy/com/cloudogu/gitops/ApplicationTest.groovy, src/test/groovy/com/cloudogu/gitops/config/schema/ConfigTest.groovy, src/test/groovy/com/cloudogu/gitops/features/ContentTest.groovy, src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy, src/test/groovy/com/cloudogu/gitops/features/RegistryTest.groovy, src/test/groovy/com/cloudogu/gitops/features/ScmManagerTest.groovy, src/test/groovy/com/cloudogu/gitops/features/argocd/ArgoCDTest.groovy
This is part of our ongoing effort to make everything opt-in.
Breaking change for local installations:  
now `--jenkins --registry --content-examples` are necessary.
When running remotely, using `registry.url` and `jenkins.url` nothing changes, but `content.examples` will have to be set to `true`.
After this only SCM-Manager is installed (if no external scm-url is passed).
=> BREAKING: Disables Jenkins, Registry, example content by default

docs/configuration.schema.json, scripts/jenkins/init-jenkins.sh, scripts/scm-manager/init-scmm.sh, src/main/groovy/com/cloudogu/gitops/config/Config.groovy, src/main/groovy/com/cloudogu/gitops/config/ConfigConstants.groovy, src/main/groovy/com/cloudogu/gitops/config/schema/JsonSchemaGenerator.groovy, src/main/groovy/com/cloudogu/gitops/features/Jenkins.groovy, src/main/groovy/com/cloudogu/gitops/features/ScmManager.groovy, src/test/groovy/com/cloudogu/gitops/features/JenkinsTest.groovy, src/test/groovy/com/cloudogu/gitops/features/ScmManagerTest.groovy
Add skipPlugins and skipRestart flags for Jenkins and SCM-Manager.
- Update config schema and CLI options
- Add env var support to feature classes
- Skip plugin install and restart in init scripts
- Extract SCM plugin install logic to installScmmPlugins
- Add tests to verify skipping behavior
Config:
```yaml
scmm: 
skipRestart: true
skipPlugins: true
jenkins:
skipRestart: true
skipPlugins: true
```
CLI Options:
```
--jenkins-skip-restart
--jenkins-skip-plugins
--scmm-skip-restart
--scmm-skip-plugins
```
=> Make Jenkins and SCM plugin install and restart optional
